export let OPEN_CATEGORY_DRAWER = 'OPEN_CATEGORY_DRAWER'
export const CLOSE_CATEGORY_DRAWER = 'CLOSE_CATEGORY_DRAWER'

export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_SUBCATEGORIES = 'SET_SUBCATEGORIES'
export const SET_SUBSUBCATEGORIES = 'SET_SUBSUBCATEGORIES'

export const CATEGORIES_FETCHING_ERROR = 'CATEGORIES_FETCHING_ERROR'
export const SUBCATEGORIES_FETCHING_ERROR = 'SUBCATEGORIES_FETCHING_ERROR'
export const SUBSUBCATEGORIES_FETCHING_ERROR = 'SUBSUBCATEGORIES_FETCHING_ERROR'

export const LOADING_CATEGORIES = 'LOADING_CATEGORIES'
export const LOADING_SUBCATEGORIES = 'LOADING_SUBCATEGORIES'
export const LOADING_SUBSUBCATEGORIES = 'LOADING_SUBSUBCATEGORIES'
