# Generated by Django 3.2.6 on 2021-08-27 12:20

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('login', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', django_fsm.FSMIntegerField(choices=[(1, 'Пользователь'), (2, 'МАГАЗИН')], default=1)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='RegularAccount',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('datebirth', models.DateField(blank=True, null=True, verbose_name='Date of birthday')),
                ('gender', django_fsm.FSMIntegerField(choices=[(1, 'Мужской'), (2, 'Женский'), (3, 'Другое'), (4, 'Не указано')], default=4, verbose_name='Gender')),
                ('clientaddress', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Regular user',
                'verbose_name_plural': 'Regular users',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('slogan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
            bases=('user.user',),
        ),
    ]
