# Generated by Django 3.2.6 on 2021-11-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210827_1224'),
        ('item', '0002_itemwithquantity_modelcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwithquantity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.store'),
        ),
        migrations.AlterField(
            model_name='modelcart',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercart', to='user.regularaccount'),
        ),
        migrations.AlterField(
            model_name='modelcart',
            name='storeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeidforcard', to='user.store'),
        ),
    ]
