# Generated by Django 3.2.6 on 2021-11-02 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210827_1224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0004_alter_itemwithquantity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCost', models.FloatField()),
                ('totalCount', models.IntegerField()),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'New'), (2, 'Packing'), (3, 'On way'), (4, 'Delivered'), (5, 'Declined'), (6, 'Declined by client')], default=1)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('declinereason', models.CharField(blank=True, max_length=200, null=True)),
                ('refusereason', models.CharField(blank=True, max_length=200, null=True)),
                ('ordertype', django_fsm.FSMIntegerField(choices=[(1, 'C доставкой'), (2, 'Самовывоз')], default=1)),
                ('phonenumber', models.CharField(blank=True, max_length=200, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.modelcart')),
                ('clientId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientId', to='user.regularaccount')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeId', to='user.store')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('total', models.FloatField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemId', to='item.item')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Idstore', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.modelorder')),
            ],
        ),
    ]
