# Generated by Django 3.2.6 on 2021-11-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_clientorderitem_modelorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelorder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='modelorder',
            name='clientId',
        ),
        migrations.RemoveField(
            model_name='modelorder',
            name='storeId',
        ),
        migrations.DeleteModel(
            name='ClientOrderItem',
        ),
        migrations.DeleteModel(
            name='ModelOrder',
        ),
    ]
