# Generated by Django 3.2.6 on 2021-11-02 16:31

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210827_1224'),
        ('item', '0006_auto_20211102_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'New'), (2, 'Packing'), (3, 'On way'), (4, 'Delivered'), (5, 'Declined'), (6, 'Declined by client')], default=1)),
                ('ordertype', django_fsm.FSMIntegerField(choices=[(1, 'C доставкой'), (2, 'Самовывоз')], default=1)),
                ('declinereason', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.modelcart')),
                ('clientId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientId', to='user.regularaccount')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeId', to='user.store')),
            ],
        ),
    ]
