# Generated by Django 3.2.6 on 2021-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_modelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
