# Generated by Django 3.2.6 on 2021-11-30 13:09

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='ordertype',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Delivery'), (2, 'Pick up')], default=1),
        ),
    ]
