# Generated by Django 3.2.6 on 2021-12-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uniqueid',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
