# Generated by Django 3.2.6 on 2022-01-02 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0013_item_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='supplier',
        ),
        migrations.AddField(
            model_name='category',
            name='supplier',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
