# Generated by Django 3.2.6 on 2022-01-16 09:35

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20220102_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcart',
            name='isavailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, 'New'), (2, 'Packing'), (3, 'On way'), (4, 'Delivered'), (5, 'Declined')], default=1),
        ),
    ]
