# Generated by Django 3.2.6 on 2022-01-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20220116_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwithquantity',
            name='isavailable',
            field=models.BooleanField(default=True),
        ),
    ]
